-- BARAMEEL RUN V23.2 — keep receipt reward Marks in the shared Marks balance
begin;
create or replace function public.claim_receipt_reward(p_player_id uuid,p_receipt_code text,p_idempotency_key text) returns jsonb language plpgsql security definer set search_path=public as $$
declare rc public.receipt_codes%rowtype;existing public.receipt_claims%rowtype;chosen public.receipt_reward_pool%rowtype;total_weight numeric:=0;target numeric;cumulative numeric:=0;rec record;piece public.collection_pieces%rowtype;chosen_image public.collection_images%rowtype;claim_id uuid;
begin
if p_idempotency_key is not null then select * into existing from public.receipt_claims where idempotency_key=p_idempotency_key limit 1;if found then return jsonb_build_object('ok',true,'idempotent',true,'claim_id',existing.id,'reward_type',existing.reward_type,'reward_label',existing.reward_label,'points_awarded',existing.points_awarded,'marks_awarded',existing.marks_awarded,'product_code',existing.product_code);end if;end if;
select * into rc from public.receipt_codes where code=upper(trim(p_receipt_code)) for update;if not found then raise exception using errcode='P0001',message='RECEIPT_CODE_INVALID';end if;if rc.status<>'UNUSED' then raise exception using errcode='P0001',message='RECEIPT_CODE_ALREADY_USED';end if;
select sum(weight) into total_weight from public.receipt_reward_pool where active and weight>0;if coalesce(total_weight,0)<=0 then raise exception using errcode='P0001',message='RECEIPT_REWARD_POOL_NOT_CONFIGURED';end if;target:=random()*total_weight;
for rec in select * from public.receipt_reward_pool where active and weight>0 order by id loop cumulative:=cumulative+rec.weight;if cumulative>=target then chosen:=rec;exit;end if;end loop;if chosen.id is null then raise exception using errcode='P0001',message='RECEIPT_DRAW_FAILED';end if;
if chosen.reward_type='PIECE' then select cp.* into piece from public.collection_pieces cp where cp.active and (chosen.piece_rarity is null or upper(cp.rarity)=upper(chosen.piece_rarity)) and not exists(select 1 from public.player_pieces pp where pp.player_id=p_player_id and pp.piece_id=cp.id) order by random() limit 1;if piece.id is not null then insert into public.player_pieces(player_id,piece_id) values(p_player_id,piece.id) on conflict(player_id,piece_id) do update set obtain_count=public.player_pieces.obtain_count+1;select * into chosen_image from public.collection_images where id=piece.image_id;end if;end if;
insert into public.receipt_claims(receipt_code,player_id,reward_id,reward_type,reward_label,points_awarded,marks_awarded,product_code,piece_id,idempotency_key,metadata) values(rc.code,p_player_id,chosen.id,chosen.reward_type,chosen.reward_label,chosen.points_awarded,chosen.marks_awarded,chosen.product_code,piece.id,p_idempotency_key,jsonb_build_object('collection_id',chosen_image.collection_id,'image_id',piece.image_id,'piece_number',piece.piece_number)) returning id into claim_id;
update public.receipt_codes set status='CONSUMED',consumed_at=now(),player_id=p_player_id,reward_id=chosen.id,metadata=metadata||jsonb_build_object('claim_id',claim_id) where code=rc.code;update public.players set points=points+chosen.points_awarded,weekly_points=weekly_points+chosen.points_awarded,marks=coalesce(marks,0)+coalesce(chosen.marks_awarded,0) where id=p_player_id;
return jsonb_build_object('ok',true,'claim_id',claim_id,'reward_type',chosen.reward_type,'reward_label',chosen.reward_label,'points_awarded',chosen.points_awarded,'marks_awarded',chosen.marks_awarded,'product_code',chosen.product_code,'collection_id',chosen_image.collection_id,'image_id',piece.image_id,'piece_number',piece.piece_number);
end;$$;
revoke all on function public.claim_receipt_reward(uuid,text,text) from public,anon,authenticated;grant execute on function public.claim_receipt_reward(uuid,text,text) to service_role;
commit;
